spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem://localhost/~/playground
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
security:
  jwt:
    token:
      secret-key: WBD_secret_key
      expire-length: 3600000
